
# ### POWERLEVEL9K SETTINGS ############################################################################

# POWERLEVEL9K_MODE='nerdfont-complete'

# # Double-Lined Prompt
# POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
# POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{014}╭%F{cyan}"
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "

# # SHORTEN
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"

# # NVM
# POWERLEVEL9K_NVM_BACKGROUND='28'
# POWERLEVEL9K_NVM_FOREGROUND='15'

# #OS Icon
# POWERLEVEL9K_OS_ICON_BACKGROUND="white"
# POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

# # Time
# #POWERLEVEL9K_TIME_FORMAT="\UF43A %D{%H:%M  \UF133  %m.%d.%y}"
# POWERLEVEL9K_TIME_FORMAT="\UF43A %D{%H:%M}"
# POWERLEVEL9K_TIME_BACKGROUND='white'
# POWERLEVEL9K_TIME_FOREGROUND='black'

# # CommandExecutionTime
# POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='red'
# POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='yellow'

# # Side
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir nvm vcs)
# # POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time zsh_showStatus time)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)
